// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KiwiLadyShoes.Models;

public partial class Wish
{
    public int WishId { get; set; }

    public int ShoeId { get; set; }

    public string UserId { get; set; }

    public virtual Shoe Shoe { get; set; }

    public virtual AspNetUser User { get; set; }
}